#!/bin/bash

# usage: ./savelogs <destination>

# tar's and cp's the logs from <logfile_scratch> to <destination>
# deletes <logfile_scratch>
# write protects <destination>

set -e

export RENDER_PATH=/groups/mousebrainmicro/mousebrainmicro/Software/barycentric
#export RENDER_PATH=/home/arthurb/projects/mouselight
export JULIA=/usr/local/julialang-0.3.8/bin/julia

# get vars from parameters.jl file
read -a tmp <<< $($JULIA -L $1/set_parameters.jl -e "print(logfile_scratch)")
logfile_scratch=${tmp[0]}

echo tar\'ing log files in $logfile_scratch
cd $logfile_scratch
tar czf $1/logs.tar.gz *log

echo deleting logfile_scratch = $logfile_scratch
rm -rf $logfile_scratch

echo write protecting destination = $1
chmod -R a-w $1
