#!/bin/bash

# usage: ./monitor <jobname> <path_to_set_parameters.jl>

# echo watch -n 60 tail -n '$((LINES-2))' $logfile_scratch/monitor.log

jobname=$1
parametersjl=$2

interval=600   # in seconds

export RENDER_PATH=/groups/mousebrainmicro/mousebrainmicro/Software/barycentric6
export JULIA=/groups/mousebrainmicro/mousebrainmicro/Software/barycentric6/julia-1.8.3/bin/julia

export JULIA_PROJECT=$RENDER_PATH/src/render 
export JULIA_DEPOT_PATH=$(dirname $(dirname $JULIA))/local/share/julia

read -a tmp <<< $($JULIA -L $parametersjl -e "print(destination,' ',local_scratch,' ',shared_scratch,' ',logfile_scratch)")
destination=${tmp[0]}
local_scratch=${tmp[1]}
shared_scratch=${tmp[2]}
logfile_scratch=${tmp[3]}

outofString=$(grep "channels split into" ${logfile_scratch}/director.log)
while [ -z "$outofString" ]; do
  sleep 60
  outofString=$(grep "channels split into" ${logfile_scratch}/director.log)
done
outofArray=($outofString)
outof=${outofArray[3]}

display_it() {
  if [ -n "$2" ] ; then
    echo $1
    echo "$2"
    echo
  fi; }

human_readable() {  # assumes $1 is in KB
  if [ "${#1}" -gt "9" ] ; then
    echo ${1:0:-9}T
  elif [ "${#1}" -gt "6" ] ; then
    echo ${1:0:-6}G
  elif [ "${#1}" -gt "3" ] ; then
    echo ${1:0:-3}M
  else
    echo ${1}B
  fi; }

START=$(date +%s)
while true ; do

  # list the nodes
  data=$(bjobs -o "name:15 stat: alloc_slot:")
  readarray -t alljobs < <(echo "$data" | tr -s ' ' | cut -s -f1 -d ' ' | cut -f1 -d '[')
  readarray -t allstates < <(echo "$data" | tr -s ' ' | cut -s -f2 -d ' ')
  readarray -t allnodes < <(echo "$data" | tr -s ' ' | cut -s -f3 -d ' ' | cut -f2 -d '*')
  readarray -t alllogs < <(echo "$data" | tr -s ' ' | cut -s -f1 -d ' ' | sed -e 's/$/[]/' | cut -f2 -d '[' | cut -f1 -d ']')
  nodes=()
  logs=()
  squatterornot=()
  cont=0
  for i in $(seq 0 $((${#alljobs[@]} - 1))) ; do
    if [ ${alljobs[$i]%[0-9]} == $jobname ] ; then
      cont=1
      if [ ${allstates[$i]} == "RUN" ] ; then
        nodes+=(${allnodes[i]})
        logs+=(${alllogs[i]}.log)
        if [ "${alljobs[$i]}" == "${jobname}1" ] ; then
          squatterornot+=(1)
        else
          squatterornot+=(0)
        fi
      fi
    fi
  done

  if [ $cont == 0 ] ; then
    echo FINISHED!
    break
  fi

  # query nodes for data
  started=$(stat -c %y $destination/set_parameters.jl)
  ntiles=$(grep "reading input tile" $logfile_scratch/*log | wc -l)
  sharedscratch1=$( grep -s -E "(receive|write) output" $logfile_scratch/squatter*.log | wc -l )
  sharedscratch2=($(df -h $shared_scratch))
  destination1=$( grep -s -E "(copying (from|to))|(saving output)" $logfile_scratch/merge*.log | wc -l )
  destination2=($(df -h $destination))
  unset tiles
  for i in $(seq 0 $((${#nodes[@]} - 1))) ; do
    #echo ${nodes[i]}
    meminfo=$(ssh -q ${nodes[i]} cat /proc/meminfo)
    memory[i]=\
$(echo "$meminfo" | grep MemTotal:  | tr -s ' ' | cut -f2 -d ' ')' '\
$(echo "$meminfo" | grep Active:    | tr -s ' ' | cut -f2 -d ' ')' '\
$(echo "$meminfo" | grep SwapTotal: | tr -s ' ' | cut -f2 -d ' ')' '\
$(echo "$meminfo" | grep SwapFree:  | tr -s ' ' | cut -f2 -d ' ')
    localscratch[i]=$(ssh -q ${nodes[i]} df -h /scratch)
    load[i]=$(ssh -q ${nodes[i]} mpstat 1 1)
    io[i]=$(ssh -q ${nodes[i]} tail -n +3 /proc/net/dev | sed 's/.*://')
    if [ "${squatterornot[i]}" -eq "1" -a -e $logfile_scratch/squatter${logs[i]} ] ; then
      tiles[i]=$(grep -c "reading input tile" $logfile_scratch/squatter${logs[i]})
    fi
    wait
  done

  # print data to screen, and dump to log
  currtime=$(date +'%Y-%m-%d %H:%M:%S')
  echo "currently " $currtime
  echo started on ${started%%.*}
  printf "\n"

  echo $ntiles input tiles read out of $outof
  echo $sharedscratch1 output tiles saved to shared_scratch = $shared_scratch , ${sharedscratch2[10]} available
  echo $destination1 output tiles saved to destination = $destination , ${destination2[10]} available
  printf "\n"

  printf "%4s%8s" "log#" node
  printf "%17s" memory swap /scratch rx/tx
  printf "%9s%9s" %load ntiles
  printf "\n"
  for i in $(seq 0 $((${#nodes[@]} - 1))) ; do
    memoryArray=(${memory[i]})
    localscratchArray=(${localscratch[i]})
    loadArray=(${load[i]})
    ioArray=(${io[i]})
    rX[i]=0;  tX[i]=0
    for j in $(seq 16 16 $((${#ioArray[@]}-1))) ; do
      rX[i]=$(( ${rX[i]} + ${ioArray[0+$j]} ))
      tX[i]=$(( ${tX[i]} + ${ioArray[8+$j]} ))
    done
    if [ -z ${last_rX[i]+x} ] ; then
      rXMBps="--";  tXMBps="--"
    else
      rXMBps=$(( (${rX[i]} - ${last_rX[i]}) / $interval / 1024 / 1024 ))
      tXMBps=$(( (${tX[i]} - ${last_tX[i]}) / $interval / 1024 / 1024 ))
    fi
    last_rX[i]=${rX[i]};  last_tX[i]=${tX[i]}
    printf "%4s%8s" " ${logs[i]%.log}" ${nodes[i]}
    memtotal=$(human_readable ${memoryArray[0]})
    memused=$(human_readable ${memoryArray[1]})
    swaptotal=$(human_readable ${memoryArray[2]})
    swapused=$(human_readable $((${memoryArray[2]} - ${memoryArray[3]})))
    printf "%9s%8s" $memtotal $memused $swaptotal $swapused ${localscratchArray[@]:8:2}
    printf "%8sM%7sM" $rXMBps $tXMBps
    printf "%9s%9s" ${loadArray[23]} ${tiles[i]}
    printf "\n"
  done

  printf "\n"
  display_it "Seg faults" "$(grep -c 'Segmentation fault' $logfile_scratch/*log | grep -v :0)"
  display_it "all errors" "$(grep -c ERROR $logfile_scratch/*log | grep -v :0)"
  display_it "input tiles that possibly failed" "$(grep -c 'might have failed' $logfile_scratch/*log | grep -v :0)"
  display_it "all warnings" "$(grep WARNING -c $logfile_scratch/*log | grep -v :0)"

  # wait until specified interval
  while (($(date +%s) - $START < $interval)) ; do
    sleep 1
  done
  START=$(date +%s)
done
